### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ratsch** [iskana/PBWT-sec#1]
I have tried to compile the software on Centos 6.3 and on Mac OS X 10.11. I've experiencing the following problem when compiling the software.

I ran "make" in crypto-PBWT/src and got these messages.

c++ -c rot.cpp -o rot.o -O3 -I/Users/raetsch/git/software/crypto-PBWT/src/include -I/Users/raetsch/git/software/crypto-PBWT/src/../../cybozulib/include/ -I/Users/raetsch/git/software/crypto-PBWT/src/../../mie/include -I/Users/raetsch/git/software/crypto-PBWT/src/../../xbyak/ -I/Users/raetsch/git/software/crypto-PBWT/src/../../Lifted-ElGamal/include/ -I/Users/raetsch/git/software/crypto-PBWT/src/../include/ -fopenmp
rot.cpp:1:29: fatal error: cybozu/option.hpp: No such file or directory
compilation terminated.
...
In file included from rot.cpp:2:
/cbio/grlab/home/raetsch/git/software/crypto-PBWT/src/../include/rot.h:3:39: error: cybozu/random_generator.hpp: No such file or directory
/cbio/grlab/home/raetsch/git/software/crypto-PBWT/src/../include/rot.h:4:29: error: cybozu/crypto.hpp: No such file or directory
/cbio/grlab/home/raetsch/git/software/crypto-PBWT/src/../include/rot.h:5:22: error: mie/fp.hpp: No such file or directory
/cbio/grlab/home/raetsch/git/software/crypto-PBWT/src/../include/rot.h:6:28: error: mie/gmp_util.hpp: No such file or directory
/cbio/grlab/home/raetsch/git/software/crypto-PBWT/src/../include/rot.h:7:27: error: mie/elgamal.hpp: No such file or directory
/cbio/grlab/home/raetsch/git/software/crypto-PBWT/src/../include/rot.h:8:27: error: mie/ecparam.hpp: No such file or directory

**Comment by iskana** [comment]
Currently, crypto-PBWT does not support Mac OS, because one of the required libraries does not support it. (We are considering to support Mac OS in the near future.)

For compiling on CentOS, please check if you already copied following libraries:
   git clone git://github.com/aistcrypt/Lifted-ElGamal.git
   git clone git://github.com/herumi/xbyak.git
   git clone git://github.com/herumi/mie.git
   git clone git://github.com/herumi/cybozulib.git
   git clone git://github.com/herumi/cybozulib_ext.git

For more information about the installation requirements, please see: https://github.com/iskana/crypto-PBWT#installation-requirements.
